# Nom de l'application
spring.application.name=foodexpress

# Profil actif par défaut (développement)
spring.profiles.active=dev

# Port du serveur
server.port=8080

# Bonne pratique : désactiver Open-In-View (évite les requêtes SQL dans les vues)
spring.jpa.open-in-view=false